global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "main"
      file_sd_configs:
          - files:
                - "/etc/prometheus/targets.json"
      metrics_path: /metrics
      static_configs:
          - targets: ["localhost:9090"] # Prometheus self-scraping target

rule_files:
    - "alert_rules.yml"
