name: CI/CD for Discord Role Selector Bot

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    lint:
        name: Lint
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install flake8
              run: |
                  pip install flake8
            - name: Lint with flake8
              run: |
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    test:
        name: Test
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install pytest
              run: |
                  pip install pytest
            - name: Test with pytest
              run: |
                  pytest

    deploy:
        name: Deploy to AWS Lightsail
        needs: test
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.LIGHTSAIL_HOST }}
                  username: ${{ secrets.LIGHTSAIL_USERNAME }}
                  key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
                  script: |
                      cd /home/ec2-user/discord-role-selector-bot
                      git pull origin master
                      ./start_app.sh
